Style/Encoding:
  Enabled: false
Metrics/LineLength:
  Max: 150
Lint/SuppressedException: 
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Style/NilComparison:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
